[project]
name = "essay-writing-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.6",
    "jupyterlab>=4.4.5",
    "openai>=1.98.0",
    "pydantic>=2.11.7",
]
